import * as React from 'react'
import './gallery.scss'
import pathToName from '../../utils/pathToName'
export interface GalleryProps {
    captures: any
    tabSelected: (tab: string) => void
}

export default class Gallery extends React.Component<GalleryProps> {
    render = () => {
        const keys = this.props.captures ? Object.keys(this.props.captures) : []
        return (
            <div className='gallery-container'>
                <h1 className='gallery-header'>Available Snaps</h1>
                <p className='gallery-intro'>Here's a list of all the snaps generated by the team. Feel free to use them, or click the button above to generate your own!</p>
                <div className='gallery'>
                    {keys.map(k => (
                        <div className='gallery-tab' key={k} onClick={() => this.props.tabSelected(k)}>
                            <img src={this.props.captures[k][0]}></img>
                            <p className='gallery-name' > {pathToName(k)} </p>
                        </div>
                    ))}
                </div>
            </div>
        )
    }
}